# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1250, 835)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/warf_parser_mini_imresizer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: #1e263e;\n"
"color: white;\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.marketTable = QtWidgets.QTableWidget(self.centralwidget)
        self.marketTable.setGeometry(QtCore.QRect(4, 130, 1245, 611))
        self.marketTable.setFocusPolicy(QtCore.Qt.NoFocus)
        self.marketTable.setToolTip("")
        self.marketTable.setStyleSheet("QHeaderView::section {\n"
"    background-color: #2b2b2b; /*шапка таблицы*/\n"
"    color: #ffffff;\n"
"    padding: 6px;\n"
"    border: 1px solid #444;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QHeaderView::section:hover {\n"
"    background-color: #3a3a3a; /*подсветка при наведении*/\n"
"}\n"
"\n"
"QTableWidget#marketTable {\n"
"    alternate-background-color: #18282f; \n"
"    background-color: #22323a;\n"
"    color: #efecec;\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: #2b2b2b; /* совпадает с фоном заголовков */\n"
"    border: 1px solid #444;    /* если нужен контур */\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QTableWidget::item:selected:!active {\n"
"    background-color: #418fa5;\n"
"    color: #18252a;\n"
"}\n"
"\n"
"QToolTip {\n"
"    background-color: efecec; \n"
"    color: #2b2b2b;\n"
"    padding: 5px;\n"
"}")
        self.marketTable.setAlternatingRowColors(True)
        self.marketTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.marketTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.marketTable.setWordWrap(True)
        self.marketTable.setRowCount(2)
        self.marketTable.setColumnCount(8)
        self.marketTable.setObjectName("marketTable")
        item = QtWidgets.QTableWidgetItem()
        self.marketTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.marketTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.marketTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.marketTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.marketTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.marketTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.marketTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.marketTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.marketTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.marketTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.marketTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.marketTable.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.marketTable.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.marketTable.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.marketTable.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.marketTable.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.marketTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.marketTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.marketTable.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.marketTable.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.marketTable.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.marketTable.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.marketTable.setItem(1, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.marketTable.setItem(1, 7, item)
        self.marketTable.horizontalHeader().setCascadingSectionResizes(True)
        self.marketTable.horizontalHeader().setDefaultSectionSize(135)
        self.add_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_btn.setGeometry(QtCore.QRect(445, 770, 171, 28))
        self.add_btn.setStyleSheet("color: #18252a;\n"
"background-color: #418fa5;\n"
"font-weight: bold;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/assignment_add_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_btn.setIcon(icon1)
        self.add_btn.setObjectName("add_btn")
        self.delete_btn = QtWidgets.QPushButton(self.centralwidget)
        self.delete_btn.setGeometry(QtCore.QRect(675, 770, 171, 28))
        self.delete_btn.setStyleSheet("color: #18252a;\n"
"background-color: #418fa5;\n"
"font-weight: bold;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/delete_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_btn.setIcon(icon2)
        self.delete_btn.setObjectName("delete_btn")
        self.buy_btn = QtWidgets.QPushButton(self.centralwidget)
        self.buy_btn.setGeometry(QtCore.QRect(1130, 180, 111, 28))
        self.buy_btn.setStyleSheet("QPushButton {\n"
"color: #418fa5;\n"
"border: 1px solid #418fa5;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #51cdd5;\n"
"    color: #171e21;\n"
"}\n"
"\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/markdown_paste_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buy_btn.setIcon(icon3)
        self.buy_btn.setObjectName("buy_btn")
        self.buy_btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.buy_btn_2.setGeometry(QtCore.QRect(1130, 215, 111, 28))
        self.buy_btn_2.setStyleSheet("QPushButton {\n"
"color: #418fa5;\n"
"border: 1px solid #418fa5;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #51cdd5;\n"
"    color: #171e21;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/search_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buy_btn_2.setIcon(icon4)
        self.buy_btn_2.setObjectName("buy_btn_2")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(1, 0, 1238, 130))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 10, 0, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logo_label = QtWidgets.QLabel(self.layoutWidget)
        self.logo_label.setEnabled(True)
        self.logo_label.setObjectName("logo_label")
        self.horizontalLayout.addWidget(self.logo_label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, 70, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setStyleSheet("color: #efecec;\n"
"font-weight: bold;")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setStyleSheet("color: #efecec;\n"
"font-weight: bold;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setStyleSheet("color: #efecec;\n"
"font-weight: bold;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setStyleSheet("color: #efecec;\n"
"font-weight: bold;")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setStyleSheet("color: #efecec;\n"
"font-weight: bold;")
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.market_logo_label = QtWidgets.QLabel(self.layoutWidget)
        self.market_logo_label.setOpenExternalLinks(True)
        self.market_logo_label.setObjectName("market_logo_label")
        self.horizontalLayout.addWidget(self.market_logo_label)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WarframeParser"))
        item = self.marketTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Иконка"))
        item = self.marketTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Имя игрока"))
        item = self.marketTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Предмет"))
        item.setToolTip(_translate("MainWindow", "предмет с маркета"))
        item = self.marketTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Тип операции"))
        item.setToolTip(_translate("MainWindow", "покупка/продажа"))
        item = self.marketTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Количество"))
        item.setToolTip(_translate("MainWindow", "кол-во предметов"))
        item = self.marketTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Текущая цена"))
        item = self.marketTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Желаемая цена"))
        item.setToolTip(_translate("MainWindow", "ожидаемая цена"))
        item = self.marketTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "График цен"))
        __sortingEnabled = self.marketTable.isSortingEnabled()
        self.marketTable.setSortingEnabled(False)
        item = self.marketTable.item(0, 0)
        item.setText(_translate("MainWindow", "-"))
        item = self.marketTable.item(0, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.marketTable.item(0, 5)
        item.setText(_translate("MainWindow", "-"))
        item = self.marketTable.item(0, 7)
        item.setText(_translate("MainWindow", "-"))
        item = self.marketTable.item(1, 0)
        item.setText(_translate("MainWindow", "-"))
        item = self.marketTable.item(1, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.marketTable.item(1, 5)
        item.setText(_translate("MainWindow", "-"))
        item = self.marketTable.item(1, 7)
        item.setText(_translate("MainWindow", "-"))
        self.marketTable.setSortingEnabled(__sortingEnabled)
        self.add_btn.setText(_translate("MainWindow", "Добавить запись"))
        self.delete_btn.setText(_translate("MainWindow", "Удалить запись"))
        self.buy_btn.setText(_translate("MainWindow", "Купить"))
        self.buy_btn_2.setText(_translate("MainWindow", "Поиск"))
        self.logo_label.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/icons/warf_parser_ic_big_imresizer.png\"/></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Инстукция к применению: "))
        self.label_2.setText(_translate("MainWindow", "1.  Выберите желаемый предмет на сайте Warframe.market."))
        self.label_3.setText(_translate("MainWindow", "2.  Заполните необходимые пункты, такие как \"Предмет\", \"Тип операции\", \"Количество\", \"Желаемая цена\"."))
        self.label_4.setText(_translate("MainWindow", "3.  Нажмите на кнопку \"Поиск\" справа от записи."))
        self.label_5.setText(_translate("MainWindow", "4.  Ожидайте по регулярно обновляемым данным, пока цена не достигнет указанного вами значения."))
        self.market_logo_label.setText(_translate("MainWindow", "<a href=\"https://warframe.market/\">\n"
"    <img src=\":/icons/wf_market_logo.png\">\n"
"</a>"))
import res_icon_rc
